---
- hosts: nodes
  user: ubuntu
  become: yes
  vars_files:
    - vars/variables.yml
  tasks:
  - name: Revoke SSH access
    authorized_key:
      user: "{{user_name}}"
      state: absent
      key: "{{ lookup('file','/home/ubuntu/.ssh/id_rsa.pub') }}"

  - name: Remove user
    user:
      name: "{{user_name}}"
      state: absent
      remove: yes

